### ISSUE TITLE
Time Zone adjustment

### ISSUE THREAD

**Issue by Mugbaz** [tcox8/OSD-Reporting#10]
Could the time zone adjustments be implemented as a variable, or checked from server clock to comply with DST adjustments?

**Comment by tcox8** [comment]
Planned fix in ver. 2.6.

**Comment by tcox8** [comment]
@Mugbaz  Can you please try the code in Version 2.6? I am able to test to a limit using powershell and set-culture but it isn't a perfect test. My limited testing seemed successful. (this comment is also on issue #11)

Link to Code: [LINK](https://github.com/tcox8/OSD-Reporting/blob/Ver2.6/OSDReporting.ps1)

**Comment by tcox8** [comment]
@Mugbaz Note: There are no added parameters. The script should detect location.

**Comment by tcox8** [comment]
Issue confirmed fixed in Code Ver2.6
