### ISSUE TITLE
Report timestamps

### ISSUE THREAD

**Issue by Mugbaz** [tcox8/OSD-Reporting#11]
Method of changing report timestamps from month/day/year format to day.month.year (or other) without the need of altering the ps1 file.

**Comment by tcox8** [comment]
Planned fix in ver. 2.6.

**Comment by tcox8** [comment]
@Mugbaz  Can you please try the code in Version 2.6? I am able to test to a limit using powershell and set-culture but it isn't a perfect test. My limited testing seemed successful.

Link to Code: [LINK](https://github.com/tcox8/OSD-Reporting/blob/Ver2.6/OSDReporting.ps1)

**Comment by tcox8** [comment]
@Mugbaz Note: There are no added parameters. The script should detect location.

**Comment by Mugbaz** [comment]
The date punctuation changed correctly from slashes to dots, but it's still showing in the wrong order (month.day.year) for my region. My region uses day.month.year

**Comment by tcox8** [comment]
@Mugbaz Can you confirm what region are you in? Can you please povide the results of "Get-Culture" in powershell? Thanks!

**Comment by Mugbaz** [comment]
```
PS> Get-Culture
LCID             Name             DisplayName
----             ----             -----------
1035             fi-FI            Finnish (Finland)

PS> (Get-Culture).DateTimeFormat.ShortDatePattern
d.M.yyyy
```

**Comment by tcox8** [comment]
@Mugbaz Please test the Ver2.6 code again. I made changes in the code around lines 483-501. Testing for me showed it was successful. Please report back on your findings. Thanks!

Link: [Ver2.6](https://github.com/tcox8/OSD-Reporting/blob/Ver2.6/OSDReporting.ps1)

**Comment by Mugbaz** [comment]
I'm getting a lot of `"String was not recognized as a valid DateTime."` errors now. Would this be of any help? [PowerShell [DateTime] throws the error "String was not recognized as a valid DateTime."](https://docs.microsoft.com/en-us/archive/blogs/dsheehan/powershell-datetime-throws-the-error-string-was-not-recognized-as-a-valid-datetime)

**Comment by tcox8** [comment]
@Mugbaz Sorry for such a long delay, I've been swamped at work. Please test the Ver2.6.1 code.  I updated the code to match the URL you provided (thanks for that!).  Please report back on your findings. Thanks!

Link: [Ver2.6.1](https://github.com/tcox8/OSD-Reporting/blob/Ver2.6.1/OSDReporting.ps1)
