### ISSUE TITLE
Could you pls further explain what entries to put in the scheduled tasks?

### ISSUE THREAD

**Issue by clabbekung** [tcox8/OSD-Reporting#14]

**Comment by tcox8** [comment]
@clabbekung Can you describe where you are confused? Have you reviewed the detailed setup guide?

https://github.com/tcox8/OSD-Reporting/blob/master/DetailedSetupGuide.md

**Comment by clabbekung** [comment]
Yes i have and when i put in -TSAdvertisementID "YOURADVERTISEMENTID" -TaskSequenceID "YOURPACKAGEID" So i guess im putting the wrong entries in.. Is it the name of the OSD and the the package ID of the same or am i just beeing stupid? Rgds Claes

**Comment by tcox8** [comment]
Ahh, ok! No worries. The TSAdvertisementID will be the DeploymentID of the task sequence. (It used to be called the advertisement ID and I believe still is labeled that in the SCCM internals). To find this, just look at the deployment of your Task Sequence and right click on the columns, and Add "DeploymentID" as a column. This guy may explain it better than me: https://sccmentor.com/2014/12/05/find-out-a-deployment-from-the-deployment-id/

The TaskSequenceID will be the PackageID of the Task Sequence. 

![image](https://user-images.githubusercontent.com/7504823/121700050-8382dd80-ca9d-11eb-8799-853eec65ba96.png)

**Comment by clabbekung** [comment]
Oh ok sweet thanks so just one more question . How do u handle the deployment for unknown computers? Ie i have 2 deployments 1 for known and 1 for unknown?

**Comment by tcox8** [comment]
You can have multiple deployments by separating them with a comma! i.e. put the Deployment ID for both deployments like this: 

-TSAdvertisementID 'UHP2051F','UHPXXXXX'


Are you setting the scheduled task to run with a user that has Admin permissions in your SCCM environment? Also, make sure to check the "run with highest privileges" checkbox in the scheduled task.

**Comment by clabbekung** [comment]
thanks yet again. That was exactly what i was looking for.

Yeah i have followed the instructions.. And tested with my own acc even.. Same issue works when i run it manually but not in the taskscheduler.

**Comment by tcox8** [comment]
Are you running it from the ConfigManager site server? I would recommend you to do that.

**Comment by clabbekung** [comment]
Yes i am running it from the site server.

Wierd that it works when i run it manually with both tested accounts :)

Skickat från min iPhone

14 juni 2021 kl. 16:55 skrev tcox8 ***@***.***>:

﻿

Are you running it from the ConfigManager site server? I would recommend you to do that.

**Comment by tcox8** [comment]
Can you send screenshots of the command you are running in your scheduled task, including the parameters you are using? There shouldn't be a difference between running it manually and through the scheduled tasks. The only thing I can think of is a typo in your scheduled task.

**Comment by clabbekung** [comment]
So here is what i run.

***@***.***D7667D.16D964D0]
***@***.***D7667D.16D964D0]

And this is the output

***@***.***D7667D.16D964D0]
If i run manually with the same acc this is the output

***@***.***D7667D.16D964D0]
Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

Från: ***@***.***>
Skickat: den 17 juni 2021 21:47
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [tcox8/OSD-Reporting] Could you pls further explain what entries to put in the scheduled tasks? (#14)


Can you send screenshots of the command you are running in your scheduled task, including the parameters you are using? There shouldn't be a difference between running it manually and through the scheduled tasks. The only thing I can think of is a typo in your scheduled task.

**Comment by tcox8** [comment]
@clabbekung Can you please upload the pictures by logging into GitHub? Your email reply did not include the pictures.
